Change response code
sergeygershun/express-graphql pull request #1
Opened 2019-12-06 13:57 UTC by Kon0pelka

2019-12-06 14:02 UTC, White-Oak requested changes

2019-12-06 14:02 UTC, White-Oak commented on src/index.js
> +
```suggestion

```

2019-12-06 14:02 UTC, White-Oak commented on src/index.js
> +          setResponsCodeFn(result.errors, response);
```suggestion
          setResponseCodeFn(result.errors, response);
```

2019-12-06 14:02 UTC, White-Oak commented on src/index.js
> +      setResponsCodeFn = optionsData.setResponsCodeFn || null;
```suggestion
      setResponseCodeFn = optionsData.setResponseCodeFn || null;
```

2019-12-06 14:03 UTC, White-Oak approved these changes

2019-12-16 11:10 UTC, White-Oak requested changes

2019-12-16 11:10 UTC, White-Oak commented on src/index.js
> +          if (codes) {
это всегда true

2019-12-16 11:10 UTC, White-Oak commented on src/index.js
> +          let codes = result.errors.map(er => { return er.message.match(/\d+/)[0] })
а если message - undefined?

2019-12-16 11:13 UTC, Kon0pelka commented on src/index.js
> +          if (codes) {
```suggestion
          if (codes.length > 0) {
```

2019-12-17 20:45 UTC, White-Oak approved these changes

2019-12-17 20:45 UTC, White-Oak commented on src/index.js
> +          codes = codes.filter(code => { return code != null})
```suggestion
          codes = codes.filter(code => code != null)
```

2019-12-28 10:51 UTC, merged